resolver: lts-3.12

packages:
- '.'
- location:
    git: https://github.com/merc1031/Spock.git
    commit: c13fc9bcade9afe11b008a1c20d9498bcee34d7b

extra-deps:
- xml-extractors-0.4.0.1
- idiii-0.1.3.3
- xml2json-0.2.0.0
- Crypto-4.2.5.1
- html-entities-1.1.0.0

flags: {}

docker:
  enable: true
  stack-exe: "image"
  repo: "merc1031/stack-musl:7.10.2"


